config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "welcome#index"
  
  resources :group_activities
  resources :groups do
    resources :activities
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_activities, dependent: :destroy
  has_many :groups, through: :group_activities

  validates :name, :amount, presence: true
  validates :amount, comparison: { greater_than_or_equal_to: 0 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user
  has_many :group_activities, dependent: :destroy
  has_many :activities, through: :group_activities

  validates :name, :icon, presence: true

  def total
    @total_cost = 0
    group_activities.includes(:activity).each do |a|
      @total_cost += a.activity.amount
    end
    @total_cost
  end
end

app/models/group_activity.rb
class GroupActivity < ApplicationRecord
  belongs_to :activity
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user! unless Rails.env == 'test'
  before_action :set_activity, only: %i[show edit update destroy]

  # GET /activities or /activities.json
  def index
    @page = 'Transactions'
    @group = Group.find(params[:group_id])
    @group_activities = GroupActivity.where(group_id: params[:group_id]).order('created_at DESC')
    @activities = []
    @group_activities.each do |a|
      activity = Activity.find(a.activity_id)
      @activities << activity
    end
  end

  # GET /activities/1 or /activities/1.json
  def show; end

  # GET /activities/new
  def new
    @page = 'New Transaction'
    @id = params[:group_id]
    @name = Group.find(params[:group_id]).name
    puts @group.inspect
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit; end

  # POST /activities or /activities.json
  def create
    @activity = Activity.new(activity_params)
    @group_activity = GroupActivity.new(group: Group.find(params[:group_id]), activity: @activity)

    respond_to do |format|
      if @activity.save && @group_activity.save
        format.html do
          redirect_to "/groups/#{params[:group_id]}/activities", notice: 'Transaction was successfully created.'
        end
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1 or /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to activity_url(@activity), notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1 or /activities/1.json
  def destroy
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def activity_params
    params.require(:activity).permit(:name, :amount).merge(author: current_user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user! unless Rails.env == 'test'
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @page = 'Categories'
    @groups = Group.all
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @page = 'New Category'
    @categories = %w[Housing Transportation Food Utilities Clothing Healthcare Entertainment
                     Household Personal Miscellaneous]
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.icon = "#{@group.name}.jpg"

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_url, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name).merge(user: current_user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index; end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/group_activities_helper.rb
module GroupActivitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/_activity.html.erb
<div id="<%= dom_id activity %>" class="activity">
  <div class="activity-name">
    <%= image_tag ("transaction.png") %>
    <p><%= activity.name %></p>
  </div>

  <p>$ <%= activity.amount %></p>
</div>

app/views/activities/_form.html.erb
<div class="login">
  <div class="login-form">
    <%= form_with model: activity, url: "/groups/#{id}/activities" do |form| %>
      <% if activity.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

          <ul>
            <% activity.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.text_field :name, required: true %>
      </div>

      <div>
        <%= form.label :amount, style: "display: block" %>
        <%= form.number_field :amount, required: true %>
      </div>

      <div>
        <%= form.label :category, style: "display: block" %>
        <%= form.text_field :category, required: true, disabled: true, value: name %>
      </div>

      <div>
        <%= form.submit "Add transaction" %>
      </div>
    <% end %>

    <a href=<%= "/groups/#{id}/activities" %> id="signup-btn">Back <i class="fa-solid fa-arrow-left"></i></i></a>
  </div>
  <div>
    <%= image_tag ("new-category.jpg") %>
  </div>
</div>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render "form", activity: @activity %>

<br>

<div>
  <%= link_to "Show this activity", @activity %> |
  <%= link_to "Back to activities", activities_path %>
</div>

app/views/activities/index.html.erb
<div class="activities-total">
  <h2><%= @group.name %></h2>
  <h2>$ <%= @group.total %></h2>
</div>

<% if @activities.length.zero? %> 
  <div class="empty">
    <%= image_tag ("empty.png") %>
    <p>No transactions yet for this category. Add a transaction to see it here</p>
  </div>
<% else %>
  <div id="activities">
    <% @activities.each do |activity| %>
      <%= render activity %>
    <% end %>
  </div>
<% end %>

<%= link_to "New Transaction", "/groups/#{@group.id}/activities/new", class: 'categories-button' %>
<a href=<%= groups_path %> id="signup-btn">Back <i class="fa-solid fa-arrow-left"></i></i></a>

app/views/activities/new.html.erb
<%= render "form", activity: @activity, id: @id, name: @name %>

app/views/activities/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @activity %>

<div>
  <%= link_to "Edit this activity", edit_activity_path(@activity) %> |
  <%= link_to "Back to activities", activities_path %>

  <%= button_to "Destroy this activity", @activity, method: :delete %>
</div>

app/views/groups/_form.html.erb
<div class="login">
  <div class="login-form">
    <%= form_with(model: group) do |form| %>
      <% if group.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

          <ul>
            <% group.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :name, style: "display: block" %>
        <%= form.select :name, @categories, { :include_blank => '-- Select One --' }, required: true %>
      </div>

      <div>
        <%= form.submit 'Add category' %>
      </div>

      <a href=<%= groups_path %> id="signup-btn">Back <i class="fa-solid fa-arrow-left"></i></i></a>
    <% end %>
  </div>
  <div>
    <%= image_tag ("new-category.jpg") %>
  <div>
</div>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="group">
  <div>
    <%= image_tag (group.icon) %>
  </div>
  <div class="group-desc">
    <h2><%= group.name %></h2>
    <div class="group-links">
      <a href=<%= "/groups/#{group.id}/activities" %> id="group-open">
        <i class="fa-solid fa-door-open"></i>
      </a>
      <a href=<%= group_path(group) %> data-turbo-method="delete" id="group-delete">
        <i class="fa-solid fa-trash-can"></i>
      </a>
    </div>
    <p>Total spent: $ <%= group.total %></p>
  </div>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<div class="categories-index">
  <% if @groups.length.zero? %> 
    <div class="empty">
      <%= image_tag ("empty.png") %>
      <p>You don't have any categories saved. Create a category to see it here</p>
    </div>
  <% else %>
    <div id="groups">
      <% @groups.each do |group| %>
        <%= render group %>
      <% end %>
    </div>
  <% end %>

  <%= link_to "New Category", new_group_path, class: 'categories-button' %>
</div>

app/views/groups/new.html.erb
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if request.env['PATH_INFO'] != root_path %>
      <header>
        <% if request.env['PATH_INFO'] == groups_path || request.env['PATH_INFO'] == new_user_session_path || request.env['PATH_INFO'] == new_user_registration_path %>
          <i class="fa-solid fa-bars"></i>
        <% else %>
          <i class="fa-solid fa-arrow-left"></i>
        <% end %>
        <% if request.env['PATH_INFO'] == new_user_session_path %>
          <h2>LOGIN</h2>
        <% elsif request.env['PATH_INFO'] == new_user_registration_path %>
          <h2>REGISTER</h2>
        <% else %>
          <h2><%= @page %></h2>
        <% end %>
        <% if user_signed_in? %>
          <a href=<%= destroy_user_session_path %> data-turbo-method="delete">
            <i class="fa-solid fa-right-from-bracket" style="color: #fff;"></i>
          </a>
        <% else %>
          <p></p>
        <% end %>
      </header>
    <% end %>

    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="experience">
  <h1>Pocket Expense</h1>

  <div>
    <button id="experience-login">
      <%= link_to "Login", new_user_session_path %>
    </button>
    <button>
      <%= link_to "Sign up", new_user_registration_path %>
    </button>
  </div>
</div>